version: '1'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    command: npm run start
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./src/infrastructure/databases/init.sql:/docker-entrypoint-initdb.d/init.sql